// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.AppStart;

#nullable disable

namespace Sistema.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027130057_UsuariosExistente")]
    partial class UsuariosExistente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema.Models.ColaboradorModel", b =>
                {
                    b.Property<int>("num_empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("num_empleado"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("num_empleado");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Sistema.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Sistema.Models.asistenciaModel", b =>
                {
                    b.Property<int>("id_asistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_asistencia"));

                    b.Property<DateTime>("dias_laborales")
                        .HasColumnType("datetime2");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("hora_entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("hora_salida")
                        .HasColumnType("datetime2");

                    b.Property<int>("num_empleado")
                        .HasColumnType("int");

                    b.Property<string>("num_empleado_reloj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_asistencia");

                    b.HasIndex("num_empleado");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("Sistema.Models.asistenciaModel", b =>
                {
                    b.HasOne("Sistema.Models.ColaboradorModel", "colaborador")
                        .WithMany("Asistencias")
                        .HasForeignKey("num_empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("colaborador");
                });

            modelBuilder.Entity("Sistema.Models.ColaboradorModel", b =>
                {
                    b.Navigation("Asistencias");
                });
#pragma warning restore 612, 618
        }
    }
}
