// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.AppStart;

#nullable disable

namespace Sistema.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251013194646_AddPrimaryKeyToAsistencia")]
    partial class AddPrimaryKeyToAsistencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema.Models.ColaboradorModel", b =>
                {
                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("num_empleado")
                        .HasColumnType("int");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Sistema.Models.asistenciaModel", b =>
                {
                    b.Property<string>("colaborador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dias_laborales")
                        .HasColumnType("datetime2");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("hora_entrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("hora_salida")
                        .HasColumnType("time");

                    b.Property<int>("id_asistencia")
                        .HasColumnType("int");

                    b.ToTable("Asistencias");
                });
#pragma warning restore 612, 618
        }
    }
}
